SHOP_PET/SHOP_PET/Models/Giohang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using System.Web;
using System.Xml.Linq;

namespace SHOP_PET.Models
{
    public class Giohang
    {
        dbPetDataContext data = new dbPetDataContext();
        public int mapet { get; set; }

        [Display(Name = "Tên pet")]
        public string tenpet { get; set; }

        [Display(Name = "Ảnh bìa")]
        public string hinhpet { get; set; }

        [Display(Name = "Giá bán")]
        public Double giaban { get; set; }

        [Display(Name = "Số lượng")]
        public int iSoluong { get; set; }

        [Display(Name = "Thành tiền")]
        public Double dThanhtien
        {
            get
            {
                return iSoluong * giaban;
            }
        }
        public Giohang(int id)
        {
            //mapet = id;
            //Pet pet = data.Pets.Single(n => n.mapet == mapet);
            //tenpet = pet.tenpet;
            //hinhpet = pet.hinhpet;
            //giaban = Double.Parse(pet.giaban.ToString());
            //iSoluong = 1;

            this.mapet= id;
            //Sach sach = data.Saches.Single(n => n.masach == masach);
            Pet p = data.Pets.Single(n => n.mapet == mapet);
            tenpet = p.tenpet;
            hinhpet= p.hinhpet;
            giaban = double.Parse(p.giaban.ToString());
            iSoluong = 1;

            //this.malich = malich;
            //LichChieu lc = data.LichChieus.Single(n => n.malich == malich);
            //ma = (int)lc.maphim;
            //gia = (int)lc.gia;
            //isoLuong = 1

            //tensach = sach.tensach;
            //hinh = sach.hinh;
            //giaban = double.Parse(sach.giaban.ToString());
            //iSoluong = 1;
        }
    }
}

SHOP_PET/SHOP_PET/Controllers/GiohangController.cs
using SHOP_PET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SHOP_PET.Controllers
{
    public class GiohangController : Controller
    {
        dbPetDataContext db = new dbPetDataContext();
        // GET: Giohang
        public List<Giohang> Laygiohang()
        {
            List<Giohang> listGiohang = Session["Giohang"] as List<Giohang>;
            if (listGiohang == null)
            {
                listGiohang = new List<Giohang>();
                Session["Giohang"] = listGiohang;
            }
            return listGiohang;
        }
        public ActionResult ThemGioHang(int id, string strURL)
        {
            List<Giohang> listGiohang = Laygiohang();
            Giohang sanpham = listGiohang.Find(n => n.mapet == id);
            if (sanpham == null)
            {
                sanpham = new Giohang(id);
                listGiohang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoluong++;
                return Redirect(strURL);
            }
        }
        private int TongSoLuong()
        {
            int tsl = 0;
            List<Giohang> listGiohang = Session["GioHang"] as List<Giohang>;
            if (listGiohang != null)
            {
                tsl = listGiohang.Sum(n => n.iSoluong);
            }
            return tsl;
        }
        private int TongSoLuongSanPham()
        {
            int tsl = 0;
            List<Giohang> listGiohang = Session["GioHang"] as List<Giohang>;
            if (listGiohang != null)
            {
                tsl = listGiohang.Count;
            }
            return tsl;
        }
        private double TongTien()
        {
            double dTongTien = 0;
            List<Giohang> lstGioHang = Session["Giohang"] as List<Giohang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.dThanhtien);
            }
            return dTongTien; 
            //double tt = 0;
            //List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            //if (lstGiohang != null)
            //{
            //    tt = lstGiohang.Sum(n => n.dThanhtien);

            //}
            //return tt;
        }
        public ActionResult GioHang()
        {
            List<Giohang> listGiohang = Laygiohang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(listGiohang);
        }
        public ActionResult GioHangPartial()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return PartialView();
        }
        public ActionResult XoaGioHang(int id)
        {
            List<Giohang> listGiohang = Laygiohang();
            Giohang sanpham = listGiohang.SingleOrDefault(n => n.mapet == id);
            if (sanpham != null)
            {
                listGiohang.RemoveAll(n => n.mapet == id);
                return RedirectToAction("GioHang");
            }
            return RedirectToAction("GioHang");
        }
        public ActionResult CapnhatGiohang(int id, FormCollection collection)
        {
            List<Giohang> listGiohang = Laygiohang();
            Giohang sanpham = listGiohang.SingleOrDefault(n => n.mapet == id);
            if (sanpham != null)
            {
                sanpham.iSoluong = int.Parse(collection["txtSolg"].ToString());
            }
            return RedirectToAction("GioHang");
        }
        public ActionResult XoaTatCaGioHang(int id)
        {
            List<Giohang> listGiohang = Laygiohang();
            listGiohang.Clear();
            return RedirectToAction("GioHang");
        }


        [HttpGet]
        public ActionResult DatHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Users");
            }
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Sach");
            }
            List<Giohang> listGioHang = Laygiohang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(listGioHang);
        }
        public ActionResult DatHang(FormCollection collection)
        {
            DonHang dh = new DonHang();
            ChiTietDonHang ct = new ChiTietDonHang();
            KhachHang kh = (KhachHang)Session["TaiKhoan"];
            Pet s = new Pet();
            List<Giohang> listGioHang = Laygiohang();
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);
            dh.makh = kh.makh;
            dh.ngaydat = DateTime.Now;
            dh.ngaygiao = DateTime.Parse(ngaygiao);
            dh.giaohang = false;
            dh.thanhtoan = s.giaban*ct.soluong;
            db.DonHangs.InsertOnSubmit(dh);
            db.SubmitChanges();
            foreach (var item in listGioHang)
            {
                ChiTietDonHang ctdh = new ChiTietDonHang();
                ctdh.madon = dh.madon;
                ctdh.mapet = item.mapet;
                ctdh.soluong = item.iSoluong;
                ctdh.gia = (decimal)item.giaban*item.iSoluong;
                s = db.Pets.Single(n => n.mapet == item.mapet);
                s.soluongtong -= ctdh.soluong;
                db.SubmitChanges();
                db.ChiTietDonHangs.InsertOnSubmit(ctdh);
            }
            db.SubmitChanges();
            Session["GioHang"] = null;
            return RedirectToAction("XacnhanDonHang", "GioHang");
        }
        public ActionResult XacnhanDonhang()
        {
            return View();
        }
    }
}

SHOP_PET/SHOP_PET/Controllers/PetController.cs
using SHOP_PET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;

namespace SHOP_PET.Controllers
{
    public class PetController : Controller
    {
        dbPetDataContext db = new dbPetDataContext();
        // GET: Pet
        
        public ActionResult Index(int? page, string searchString)
        {
            ViewBag.Keyword = searchString;
            if (page == null) page = 1;
            var all_Pet = (from Pet in db.Pets select Pet).OrderBy(m => m.mapet);
            if (!string.IsNullOrEmpty(searchString)) all_Pet = (IOrderedQueryable<Pet>)all_Pet.Where(a => a.tenpet.Contains(searchString));
            int pageSize = 3;
            int pageNUM = page ?? 1;
            return View(all_Pet.ToPagedList(pageNUM, pageSize));
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Pet s)
        {
            var E_maloai = Convert.ToInt32(collection["maloai"]);
            var E_tenpet = collection["tenpet"];
            var E_hinh = collection["hinhpet"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongtong = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tenpet))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.maloai = E_maloai;
                s.tenpet = E_tenpet.ToString();
                s.hinhpet = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongtong = E_soluongtong;
                db.Pets.InsertOnSubmit(s);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "Content/images/" + file.FileName;
        }
        public ActionResult Edit(int id)
        {
            var E_pet = db.Pets.First(m => m.mapet == id);
            return View(E_pet);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_maloai = Convert.ToInt32(collection["maloai"]);
            var E_pet = db.Pets.First(m => m.mapet == id);
            var E_tenpet = collection["tenpet"];
            var E_hinh = collection["hinhpet"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongtong = Convert.ToInt32(collection["soluongtong"]);
            E_pet.mapet = id;
            if (string.IsNullOrEmpty(E_tenpet))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_pet.maloai = E_maloai;
                E_pet.tenpet = E_tenpet;
                E_pet.hinhpet = E_hinh;
                E_pet.giaban = E_giaban;
                E_pet.ngaycapnhat = E_ngaycapnhat;
                E_pet.soluongtong = E_soluongtong;
                UpdateModel(E_pet);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        public ActionResult Delete(int id)
        {
            var D_pet = db.Pets.First(m => m.mapet == id);
            return View(D_pet);

        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = db.Pets.First(m => m.mapet == id);
            db.Pets.DeleteOnSubmit(D_sach);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var st = db.Pets.Where(s => s.mapet == id).First();
            return View(st);
        }
    }
}

SHOP_PET/SHOP_PET/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SHOP_PET.Models;

namespace SHOP_PET.Controllers
{
    public class ShopController : Controller
    {
        dbPetDataContext db = new dbPetDataContext();
        // GET: Shop
        private IQueryable<Pet> FilterItemsByPrice(IQueryable<Pet> items, string price)
        {
            switch (price)
            {
                case "Chó":
                    return items.Where(it => it.maloai==1);
                case "Mèo":
                    return items.Where(it => it.maloai==2);
                case "Cá":
                    return items.Where(it => it.maloai==3);
                default:
                    return items;
            }
        }
        private List<string> GetPriceList()
        {
            return new List<string> { "Mèo", "Chó", "Cá" };
        }

        //private IQueryable<Pet> FilterItemsByPrice1(IQueryable<Pet> items, string price)
        //{
        //    switch (price)
        //    {
        //        case "Chó":
        //            return items.Where(it => it.giaban == 100);
        //        case "Mèo":
        //            return items.Where(it => it.giaban == 2000);
        //        case "Cá":
        //            return items.Where(it => it.giaban == 300);
        //        default:
        //            return items;
        //    }
        //}
        //private List<string> GetPriceList1()
        //{
        //    return new List<string> { "Mèo", "Chó", "Cá" };
        //}

        public ActionResult Home(int? size, int? page, string price, string searchString)
        {
            ViewBag.Keyword = searchString;
            
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "3", Value = "3" });
            items.Add(new SelectListItem { Text = "6", Value = "6" });
            items.Add(new SelectListItem { Text = "12", Value = "12" });
            items.Add(new SelectListItem { Text = "24", Value = "24" });
            items.Add(new SelectListItem { Text = "48", Value = "48" });
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }

            ViewBag.size = items;
            ViewBag.currentSize = size;
            ViewBag.PriceList = new SelectList(GetPriceList());
            if (page == null) page = 1;
            var all_Pet = from Pet in db.Pets select Pet;
            if (!string.IsNullOrEmpty(price))
            {
                all_Pet = FilterItemsByPrice(all_Pet, price);
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                all_Pet = all_Pet.Where(s => s.tenpet.Contains(searchString));
            }
            int pageSize = (size ?? 3);
            int pageNum = page ?? 1;
            return View(all_Pet.ToPagedList(pageNum, pageSize));
            
        }
        public ActionResult Details(int id)
        {
            var st = db.Pets.Where(s => s.mapet == id).First();
            return View(st);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SHOP_PET/SHOP_PET/Views/Giohang/DatHang.cshtml
@model IEnumerable<SHOP_PET.Models.Giohang>

@{
    ViewBag.Title = "DatHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DatHang</h2>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.mapet)</th>
        <th>@Html.DisplayNameFor(model => model.tenpet)</th>
        <th>@Html.DisplayNameFor(model => model.hinhpet)</th>
        <th>@Html.DisplayNameFor(model => model.giaban)</th>
        <th>@Html.DisplayNameFor(model => model.iSoluong)</th>
        <th>@Html.DisplayNameFor(model => model.dThanhtien)</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        @*<tr>
                <td>@Html.DisplayNameFor(model => model.mapet)</td>
                <td>@Html.DisplayNameFor(model => model.tenpet)</td>
                <td><img src="@item.hinhpet" width="200" /></td>
                @using (Html.BeginForm("CapnhatGiohang", "Giohang", new { @id = item.mapet }))
                {
                    <td>@String.Format("{0:0,0}", item.giaban)VNĐ</td>
                    <td>@Html.DisplayNameFor(model => model.iSoluong)</td>
                    <td>@Html.DisplayNameFor(model => model.dThanhtien)</td>
                }
            </tr>*@
<tr>
    <td>@Html.DisplayFor(modelItem => item.mapet)</td>
    <td>@Html.DisplayFor(modelItem => item.tenpet)</td>
    <td><img src="/@item.hinhpet" width="70" /></td>

    @using (Html.BeginForm("CapnhatGioHang", "GioHang", new { @id = item.mapet }))
    {
        <td>@String.Format("{0:0,0}", item.giaban) VNĐ </td>
        @*<td>@Html.DisplayNameFor(model => model.iSoluong)</td>*@

        <td>@item.iSoluong</td>

        <td>@Html.DisplayFor(modelItem => item.dThanhtien)</td>
    }
</tr>
    }
    <tr style="font-weight:bold;text-align:right;color:red">
        <td colspan="1">Số lượng Pet: @ViewBag.Tongsoluong</td>
        <td colspan="2">Số loại Pet: @ViewBag.Tongsoluongsanpham</td>
        <td colspan="4">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)VNĐ</td>
    </tr>
    <tr style="font-weight:bold;text-align:right">
        <td colspan="6">@Html.ActionLink("Trơ về giỏ hàng", "GioHang", "GioHang")</td>
    </tr>
</table>

@using SHOP_PET.Models
<h2 style="text-align:center">Thông tin đặt hàng</h2>
@{
    KhachHang kh = (KhachHang)Session["TaiKhoan"];
}
<table align="center">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <tr style="height:40px">
            <td>Họ tên khách hàng:</td>
            <td style="font-weight:bold">@kh.hoten</td>
        </tr>
        <tr style="height:40px">
            <td>Email:</td>
            <td style="font-weight:bold">@kh.email</td>
        </tr>
        <tr style="height:40px">
            <td>Địa chỉ:</td>
            <td style="font-weight:bold">@kh.diachi</td>
        </tr>
        <tr style="height:40px">
            <td>Điện thoại:</td>
            <td style="font-weight:bold">@kh.dienthoai</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày đặt:</td>
            <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày giao:</td>
            <td style="font-weight:bold"><input type="date" name="NgayGiao" /></td>
        </tr>
        <tr style="height:40px">
            <td></td>
            <td style="font-weight:bold"><input type="submit" value="Xác nhận" class="btn btn-success" /></td>
        </tr>
    }
</table>

SHOP_PET/SHOP_PET/Views/Giohang/GioHang.cshtml
@model IEnumerable<SHOP_PET.Models.Giohang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GIỎ HÀNG</h2>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.tenpet)</th>
        <th>@Html.DisplayNameFor(model => model.hinhpet)</th>
        <th>@Html.DisplayNameFor(model => model.giaban)</th>
        <th>@Html.DisplayNameFor(model => model.iSoluong)</th>
        <th>@Html.DisplayNameFor(model => model.dThanhtien)</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.tenpet)</td>
            <td><img src="/@item.hinhpet" width="180" /></td>
            @using (Html.BeginForm("CapnhatGiohang", "Giohang", new { @id = item.mapet }))
            {
                <td>@String.Format("{0:0,0}", item.giaban) VNĐ</td>
                <td>@item.iSoluong</td>
                @*<td><input type="number" min="1" name="txtSoLg" value="@item.iSoluong"</td>*@
                <td>@Html.DisplayFor(modelItem => item.dThanhtien)</td>
                <td><a href="@Url.Action("Detail", "Pet", new {id=item.mapet})">Chi tiết</a> | @Html.ActionLink("Xóa", "XoaGiohang", new { @id = item.mapet })</td>

            }
        </tr>
    }
<tr style="font-weight:bold; text-align:left; color:red">
    <td colspan="2">Số loại Pet: @ViewBag.Tongsoluongsanpham</td>
    <td colspan="2">Số lượng Pet: @ViewBag.Tongsoluong</td>
    <td colspan="4">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien) VNĐ</td>
    @*<td colspan="4">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)VNĐ</td>*@
</tr>
    <tr style="font-weight: bold; text-align: right; color: blue"></tr>
    @*<td colspan="5">
        @Html.ActionLink("Xóa giỏ hàng", "XoaTatCaGioHang")
    </td>*@
    <tr style="font-weight:bold; color:yellow; text-align: right"></tr>
    <td colspan="5">@Html.ActionLink("Đặt hàng", "DatHang", "Giohang")</td>
</table>

SHOP_PET/SHOP_PET/Views/Giohang/GioHangPartial.cshtml
<a class="getstarted scrollto active" href="@Url.Action("GioHang",
"GioHang")" style="font-weight:bold; text-decoration:none">
    Giỏ hàng (@ViewBag.Tongsoluongsanpham)
</a>

SHOP_PET/SHOP_PET/Views/Giohang/XacnhanDonhang.cshtml
@{
    ViewBag.Title = "XacnhanDonhang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>XÁC NHẬN ĐƠN HÀNG</h2>
<h2>Đơn hàng đã được xác nhận</h2>
<h3>Chúng tôi sẽ giao hàng cho bạn sớm nhất có thể !</h3>
<p>
    @Html.ActionLink("Về trang chủ", "Home", "Shop")
</p>